### ISSUE TITLE
Exception in log when scanning QR code

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/entitlementcard#1578]
**Describe the bug**
Sometimes after scanning a QR code, I see the following exception in the log:
```
E/flutter (14246): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _QRViewState#c58b8(lifecycle state: defunct, not mounted)
E/flutter (14246): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (14246): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (14246): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (14246): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
E/flutter (14246): #1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
E/flutter (14246): #2      _QRViewState._onCodeScanned (package:ehrenamtskarte/identification/qr_code_scanner/qr_code_scanner.dart:155:7)
E/flutter (14246): <asynchronous suspension>
E/flutter (14246): 
```
The issue is flaky and there are no specific steps to reproduce it.

**Smartphone (please complete the following information):**
Last time I observed it using an emulator, but not sure if it's device-specific
 - Device: Pixel 4
 - OS: Android 13

**Additional context**

**Comment by seluianova** [comment]
Probably fixed by https://github.com/digitalfabrik/entitlementcard/pull/1727
