### ISSUE TITLE
fix missing project on createOrUpdateRegion

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/entitlementcard#1602]
**Describe the bug**
Currently the backend service can't start because there is no koblenz project.
Normally this project will be created via `config.yml` that is generated in salt.
Currently lots of information are missing, so we could also temporary add a migration to add the project or insert it directly in the database

**To Reproduce**
1. install new package version 8.1
2. Restart backend service

**Expected behavior**
Service starts properly after installation

**Additional context**
Some log information
```bash
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]: [main] INFO Exposed - Checking mapping consistence took 223ms
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]: Exception in thread "main" java.lang.Error: Required project 'koblenz.sozialpass.app' not found!
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]:         at app.ehrenamtskarte.backend.regions.database.SetupKt.insertOrUpdateRegions$createOrUpdateRegion(Setup.kt:22)
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]:         at app.ehrenamtskarte.backend.regions.database.SetupKt.access$insertOrUpdateRegions$createOrUpdateRegion(Setup.kt:1)
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]:         at app.ehrenamtskarte.backend.regions.database.SetupKt$insertOrUpdateRegions$1.invoke(Setup.kt:63)
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]:         at app.ehrenamtskarte.backend.regions.database.SetupKt$insertOrUpdateRegions$1.invoke(Setup.kt:40)
Aug 27 13:30:20 entitlementcard-test.tuerantuer.org backend[818972]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.k>
```

**Comment by f1sh1918** [comment]
Create a salt issue because the config for koblenz is missing there
https://tasks.tuerantuer.org/work_packages/3575

**Comment by f1sh1918** [comment]
merged and deployed
