### ISSUE TITLE
Create missing categories

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#300]
Currently the category 9 is missing in the production environment. I dont really want to clean the whole db as there are user and privilege settings in there.

Therefore it would be good if categories would be updated if one is missing or out of date.

**Comment by maxammann** [comment]
```
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO acceptingstores ("categoryId", "contactId", description, "name") VALUES (9, 6883, '15 % auf alle Anwendungen ab 20,00 Euro', 'Auszeit fï¿½r Kï¿½rper und Seele')
RETURNING * was aborted: ERROR: insert or update on table "acceptingstores" violates foreign key constraint "fk_acceptingstores_categoryid_id"
  Detail: Key (categoryId)=(9) is not present in table "categories".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2286)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:521)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:870)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeBatch(JdbcPreparedStatementImpl.kt:41)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:111)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:117)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:11)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61)
	... 40 more
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "acceptingstores" violates foreign key constraint "fk_acceptingstores_categoryid_id"
  Detail: Key (categoryId)=(9) is not present in table "categories".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	... 49 more

```
