### ISSUE TITLE
Fix loading of style.json in deployment

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#588]
```
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]: Exception in thread "main" java.lang.Error: Map style 'style.json' is missing!'
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at app.ehrenamtskarte.backend.map.webservice.MapStyleHandler.loadStyle(MapStyleHandler.kt:67)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at app.ehrenamtskarte.backend.map.webservice.MapStyleHandler.<init>(MapStyleHandler.kt:20)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at app.ehrenamtskarte.backend.common.webservice.WebService.start(WebService.kt:54)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at app.ehrenamtskarte.backend.Execute.run(EntryPoint.kt:110)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
Oct 17 17:43:02 entitlementcard.tuerantuer.org backend[109661]:         at app.ehrenamtskarte.backend.EntryPointKt.main(EntryPoint.kt:115)
```

**Comment by maxammann** [comment]
fixed in #589
