### ISSUE TITLE
Exception when resetting password of a Nürnberg account on bayern.ehrenamtskarte.app

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#821]
```
eb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]: [JettyServerThreadPool-20] WARN notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler - Exception while fetching data (/result) : Collection is empty.
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]: java.util.NoSuchElementException: Collection is empty.
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:594)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at app.ehrenamtskarte.backend.auth.webservice.schema.ResetPasswordMutationService$sendResetMail$1.invoke(ResetPasswordMutationService.kt:25)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at app.ehrenamtskarte.backend.auth.webservice.schema.ResetPasswordMutationService$sendResetMail$1.invoke(ResetPasswordMutationService.kt:22)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:215)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:241)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:240)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:190)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:160)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:146)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:145)
Feb 24 07:11:07 entitlementcard.tuerantuer.org backend[18834]:         at app.ehrenamtskarte.backend.auth.webservice.schema.ResetPasswordMutationService.sendResetMail(ResetPasswordMutationService.kt:22)
```
- Check first if user exists in the project and return exception "User does not exist"

**Comment by michael-markl** [comment]
More context would be nice.

**Comment by maxammann** [comment]
First visit druckerei.ehrenematskarte.app and then click on Reset password. Now, if you try to reset the password of a user in Nürnberg, you will get an error and the exception above is printed.
